#!/usr/bin/env python
from clusto.script_helper import init_script
import clusto.drivers
import clusto

import optparse
import sys

def main():
    init_script()

    parser = optparse.OptionParser(usage='%prog [options] <driver> <name>')
    options, args = parser.parse_args()

    if len(args) < 2:
        parser.print_help()
        return -1

    drivername = args[0]
    name = args[1]

    driver = getattr(clusto.drivers, drivername)
    obj = driver(name)
    print obj

if __name__ == '__main__':
    sys.exit(main())
